#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLNhanSu")]
	public partial class QuanLyNhanSuDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertPhongBan(PhongBan instance);
    partial void UpdatePhongBan(PhongBan instance);
    partial void DeletePhongBan(PhongBan instance);
    partial void InsertKyLuat(KyLuat instance);
    partial void UpdateKyLuat(KyLuat instance);
    partial void DeleteKyLuat(KyLuat instance);
    partial void InsertKhenThuong(KhenThuong instance);
    partial void UpdateKhenThuong(KhenThuong instance);
    partial void DeleteKhenThuong(KhenThuong instance);
    partial void InsertHoSoNhanSu(HoSoNhanSu instance);
    partial void UpdateHoSoNhanSu(HoSoNhanSu instance);
    partial void DeleteHoSoNhanSu(HoSoNhanSu instance);
    partial void InsertDanToc(DanToc instance);
    partial void UpdateDanToc(DanToc instance);
    partial void DeleteDanToc(DanToc instance);
    partial void InsertChucVu(ChucVu instance);
    partial void UpdateChucVu(ChucVu instance);
    partial void DeleteChucVu(ChucVu instance);
    #endregion
		
		public QuanLyNhanSuDataContext() : 
				base(global::DAL.Properties.Settings.Default.QLNhanSuConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyNhanSuDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyNhanSuDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyNhanSuDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyNhanSuDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<PhongBan> PhongBans
		{
			get
			{
				return this.GetTable<PhongBan>();
			}
		}
		
		public System.Data.Linq.Table<KyLuat> KyLuats
		{
			get
			{
				return this.GetTable<KyLuat>();
			}
		}
		
		public System.Data.Linq.Table<KhenThuong> KhenThuongs
		{
			get
			{
				return this.GetTable<KhenThuong>();
			}
		}
		
		public System.Data.Linq.Table<HoSoNhanSu> HoSoNhanSus
		{
			get
			{
				return this.GetTable<HoSoNhanSu>();
			}
		}
		
		public System.Data.Linq.Table<DanToc> DanTocs
		{
			get
			{
				return this.GetTable<DanToc>();
			}
		}
		
		public System.Data.Linq.Table<ChucVu> ChucVus
		{
			get
			{
				return this.GetTable<ChucVu>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TaiKhoan1;
		
		private string _MatKhau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTaiKhoan1Changing(string value);
    partial void OnTaiKhoan1Changed();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    #endregion
		
		public TaiKhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TaiKhoan", Storage="_TaiKhoan1", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TaiKhoan1
		{
			get
			{
				return this._TaiKhoan1;
			}
			set
			{
				if ((this._TaiKhoan1 != value))
				{
					this.OnTaiKhoan1Changing(value);
					this.SendPropertyChanging();
					this._TaiKhoan1 = value;
					this.SendPropertyChanged("TaiKhoan1");
					this.OnTaiKhoan1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhongBan")]
	public partial class PhongBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhongBan;
		
		private string _TenPhongBan;
		
		private string _GhiChu;
		
		private EntitySet<HoSoNhanSu> _HoSoNhanSus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhongBanChanging(string value);
    partial void OnMaPhongBanChanged();
    partial void OnTenPhongBanChanging(string value);
    partial void OnTenPhongBanChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public PhongBan()
		{
			this._HoSoNhanSus = new EntitySet<HoSoNhanSu>(new Action<HoSoNhanSu>(this.attach_HoSoNhanSus), new Action<HoSoNhanSu>(this.detach_HoSoNhanSus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhongBan", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhongBan
		{
			get
			{
				return this._MaPhongBan;
			}
			set
			{
				if ((this._MaPhongBan != value))
				{
					this.OnMaPhongBanChanging(value);
					this.SendPropertyChanging();
					this._MaPhongBan = value;
					this.SendPropertyChanged("MaPhongBan");
					this.OnMaPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhongBan", DbType="NVarChar(100)")]
		public string TenPhongBan
		{
			get
			{
				return this._TenPhongBan;
			}
			set
			{
				if ((this._TenPhongBan != value))
				{
					this.OnTenPhongBanChanging(value);
					this.SendPropertyChanging();
					this._TenPhongBan = value;
					this.SendPropertyChanged("TenPhongBan");
					this.OnTenPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongBan_HoSoNhanSu", Storage="_HoSoNhanSus", ThisKey="MaPhongBan", OtherKey="MaPhongBan")]
		public EntitySet<HoSoNhanSu> HoSoNhanSus
		{
			get
			{
				return this._HoSoNhanSus;
			}
			set
			{
				this._HoSoNhanSus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoSoNhanSus(HoSoNhanSu entity)
		{
			this.SendPropertyChanging();
			entity.PhongBan = this;
		}
		
		private void detach_HoSoNhanSus(HoSoNhanSu entity)
		{
			this.SendPropertyChanging();
			entity.PhongBan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KyLuat")]
	public partial class KyLuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKyLuat;
		
		private string _MaNhanSu;
		
		private System.Nullable<System.DateTime> _NgayKL;
		
		private string _NoiDungKL;
		
		private EntityRef<HoSoNhanSu> _HoSoNhanSu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKyLuatChanging(string value);
    partial void OnMaKyLuatChanged();
    partial void OnMaNhanSuChanging(string value);
    partial void OnMaNhanSuChanged();
    partial void OnNgayKLChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKLChanged();
    partial void OnNoiDungKLChanging(string value);
    partial void OnNoiDungKLChanged();
    #endregion
		
		public KyLuat()
		{
			this._HoSoNhanSu = default(EntityRef<HoSoNhanSu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKyLuat", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKyLuat
		{
			get
			{
				return this._MaKyLuat;
			}
			set
			{
				if ((this._MaKyLuat != value))
				{
					this.OnMaKyLuatChanging(value);
					this.SendPropertyChanging();
					this._MaKyLuat = value;
					this.SendPropertyChanged("MaKyLuat");
					this.OnMaKyLuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanSu", DbType="VarChar(5)")]
		public string MaNhanSu
		{
			get
			{
				return this._MaNhanSu;
			}
			set
			{
				if ((this._MaNhanSu != value))
				{
					if (this._HoSoNhanSu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanSuChanging(value);
					this.SendPropertyChanging();
					this._MaNhanSu = value;
					this.SendPropertyChanged("MaNhanSu");
					this.OnMaNhanSuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKL", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayKL
		{
			get
			{
				return this._NgayKL;
			}
			set
			{
				if ((this._NgayKL != value))
				{
					this.OnNgayKLChanging(value);
					this.SendPropertyChanging();
					this._NgayKL = value;
					this.SendPropertyChanged("NgayKL");
					this.OnNgayKLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungKL", DbType="NVarChar(MAX)")]
		public string NoiDungKL
		{
			get
			{
				return this._NoiDungKL;
			}
			set
			{
				if ((this._NoiDungKL != value))
				{
					this.OnNoiDungKLChanging(value);
					this.SendPropertyChanging();
					this._NoiDungKL = value;
					this.SendPropertyChanged("NoiDungKL");
					this.OnNoiDungKLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoSoNhanSu_KyLuat", Storage="_HoSoNhanSu", ThisKey="MaNhanSu", OtherKey="MaNhanSu", IsForeignKey=true)]
		public HoSoNhanSu HoSoNhanSu
		{
			get
			{
				return this._HoSoNhanSu.Entity;
			}
			set
			{
				HoSoNhanSu previousValue = this._HoSoNhanSu.Entity;
				if (((previousValue != value) 
							|| (this._HoSoNhanSu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoSoNhanSu.Entity = null;
						previousValue.KyLuats.Remove(this);
					}
					this._HoSoNhanSu.Entity = value;
					if ((value != null))
					{
						value.KyLuats.Add(this);
						this._MaNhanSu = value.MaNhanSu;
					}
					else
					{
						this._MaNhanSu = default(string);
					}
					this.SendPropertyChanged("HoSoNhanSu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhenThuong")]
	public partial class KhenThuong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhenThuong;
		
		private string _MaNhanSu;
		
		private System.Nullable<System.DateTime> _NgayKT;
		
		private string _NoiDungKT;
		
		private EntityRef<HoSoNhanSu> _HoSoNhanSu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhenThuongChanging(string value);
    partial void OnMaKhenThuongChanged();
    partial void OnMaNhanSuChanging(string value);
    partial void OnMaNhanSuChanged();
    partial void OnNgayKTChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKTChanged();
    partial void OnNoiDungKTChanging(string value);
    partial void OnNoiDungKTChanged();
    #endregion
		
		public KhenThuong()
		{
			this._HoSoNhanSu = default(EntityRef<HoSoNhanSu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhenThuong", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhenThuong
		{
			get
			{
				return this._MaKhenThuong;
			}
			set
			{
				if ((this._MaKhenThuong != value))
				{
					this.OnMaKhenThuongChanging(value);
					this.SendPropertyChanging();
					this._MaKhenThuong = value;
					this.SendPropertyChanged("MaKhenThuong");
					this.OnMaKhenThuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanSu", DbType="VarChar(5)")]
		public string MaNhanSu
		{
			get
			{
				return this._MaNhanSu;
			}
			set
			{
				if ((this._MaNhanSu != value))
				{
					if (this._HoSoNhanSu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanSuChanging(value);
					this.SendPropertyChanging();
					this._MaNhanSu = value;
					this.SendPropertyChanged("MaNhanSu");
					this.OnMaNhanSuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKT", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayKT
		{
			get
			{
				return this._NgayKT;
			}
			set
			{
				if ((this._NgayKT != value))
				{
					this.OnNgayKTChanging(value);
					this.SendPropertyChanging();
					this._NgayKT = value;
					this.SendPropertyChanged("NgayKT");
					this.OnNgayKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungKT", DbType="NVarChar(MAX)")]
		public string NoiDungKT
		{
			get
			{
				return this._NoiDungKT;
			}
			set
			{
				if ((this._NoiDungKT != value))
				{
					this.OnNoiDungKTChanging(value);
					this.SendPropertyChanging();
					this._NoiDungKT = value;
					this.SendPropertyChanged("NoiDungKT");
					this.OnNoiDungKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoSoNhanSu_KhenThuong", Storage="_HoSoNhanSu", ThisKey="MaNhanSu", OtherKey="MaNhanSu", IsForeignKey=true)]
		public HoSoNhanSu HoSoNhanSu
		{
			get
			{
				return this._HoSoNhanSu.Entity;
			}
			set
			{
				HoSoNhanSu previousValue = this._HoSoNhanSu.Entity;
				if (((previousValue != value) 
							|| (this._HoSoNhanSu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoSoNhanSu.Entity = null;
						previousValue.KhenThuongs.Remove(this);
					}
					this._HoSoNhanSu.Entity = value;
					if ((value != null))
					{
						value.KhenThuongs.Add(this);
						this._MaNhanSu = value.MaNhanSu;
					}
					else
					{
						this._MaNhanSu = default(string);
					}
					this.SendPropertyChanged("HoSoNhanSu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoSoNhanSu")]
	public partial class HoSoNhanSu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhanSu;
		
		private string _TenNS;
		
		private string _Anh;
		
		private string _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _NoiSinh;
		
		private string _QueQuan;
		
		private string _HoKhauThuongTru;
		
		private System.Nullable<int> _CMND;
		
		private System.Nullable<System.DateTime> _NgayCap;
		
		private string _NoiCap;
		
		private string _QuocTich;
		
		private string _TonGiao;
		
		private string _MaDanToc;
		
		private string _MaCV;
		
		private string _MaPhongBan;
		
		private System.Nullable<int> _SDT;
		
		private string _Email;
		
		private string _NhomMau;
		
		private string _ChieuCao;
		
		private string _CanNang;
		
		private string _SucKhoe;
		
		private string _TinhTrangHonNhan;
		
		private string _ThanhPhanGiaDinh;
		
		private string _DangVien;
		
		private System.Nullable<System.DateTime> _NgayVaoDoan;
		
		private System.Nullable<System.DateTime> _NgayVaoDang;
		
		private string _TrinhDoVanHoa;
		
		private string _TotNghiep;
		
		private string _NganhDaoTao;
		
		private string _Loai;
		
		private string _HocVi;
		
		private string _NgoaiNgu;
		
		private EntitySet<KyLuat> _KyLuats;
		
		private EntitySet<KhenThuong> _KhenThuongs;
		
		private EntityRef<PhongBan> _PhongBan;
		
		private EntityRef<DanToc> _DanToc;
		
		private EntityRef<ChucVu> _ChucVu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanSuChanging(string value);
    partial void OnMaNhanSuChanged();
    partial void OnTenNSChanging(string value);
    partial void OnTenNSChanged();
    partial void OnAnhChanging(string value);
    partial void OnAnhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnNoiSinhChanging(string value);
    partial void OnNoiSinhChanged();
    partial void OnQueQuanChanging(string value);
    partial void OnQueQuanChanged();
    partial void OnHoKhauThuongTruChanging(string value);
    partial void OnHoKhauThuongTruChanged();
    partial void OnCMNDChanging(System.Nullable<int> value);
    partial void OnCMNDChanged();
    partial void OnNgayCapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapChanged();
    partial void OnNoiCapChanging(string value);
    partial void OnNoiCapChanged();
    partial void OnQuocTichChanging(string value);
    partial void OnQuocTichChanged();
    partial void OnTonGiaoChanging(string value);
    partial void OnTonGiaoChanged();
    partial void OnMaDanTocChanging(string value);
    partial void OnMaDanTocChanged();
    partial void OnMaCVChanging(string value);
    partial void OnMaCVChanged();
    partial void OnMaPhongBanChanging(string value);
    partial void OnMaPhongBanChanged();
    partial void OnSDTChanging(System.Nullable<int> value);
    partial void OnSDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNhomMauChanging(string value);
    partial void OnNhomMauChanged();
    partial void OnChieuCaoChanging(string value);
    partial void OnChieuCaoChanged();
    partial void OnCanNangChanging(string value);
    partial void OnCanNangChanged();
    partial void OnSucKhoeChanging(string value);
    partial void OnSucKhoeChanged();
    partial void OnTinhTrangHonNhanChanging(string value);
    partial void OnTinhTrangHonNhanChanged();
    partial void OnThanhPhanGiaDinhChanging(string value);
    partial void OnThanhPhanGiaDinhChanged();
    partial void OnDangVienChanging(string value);
    partial void OnDangVienChanged();
    partial void OnNgayVaoDoanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayVaoDoanChanged();
    partial void OnNgayVaoDangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayVaoDangChanged();
    partial void OnTrinhDoVanHoaChanging(string value);
    partial void OnTrinhDoVanHoaChanged();
    partial void OnTotNghiepChanging(string value);
    partial void OnTotNghiepChanged();
    partial void OnNganhDaoTaoChanging(string value);
    partial void OnNganhDaoTaoChanged();
    partial void OnLoaiChanging(string value);
    partial void OnLoaiChanged();
    partial void OnHocViChanging(string value);
    partial void OnHocViChanged();
    partial void OnNgoaiNguChanging(string value);
    partial void OnNgoaiNguChanged();
    #endregion
		
		public HoSoNhanSu()
		{
			this._KyLuats = new EntitySet<KyLuat>(new Action<KyLuat>(this.attach_KyLuats), new Action<KyLuat>(this.detach_KyLuats));
			this._KhenThuongs = new EntitySet<KhenThuong>(new Action<KhenThuong>(this.attach_KhenThuongs), new Action<KhenThuong>(this.detach_KhenThuongs));
			this._PhongBan = default(EntityRef<PhongBan>);
			this._DanToc = default(EntityRef<DanToc>);
			this._ChucVu = default(EntityRef<ChucVu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanSu", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhanSu
		{
			get
			{
				return this._MaNhanSu;
			}
			set
			{
				if ((this._MaNhanSu != value))
				{
					this.OnMaNhanSuChanging(value);
					this.SendPropertyChanging();
					this._MaNhanSu = value;
					this.SendPropertyChanged("MaNhanSu");
					this.OnMaNhanSuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNS", DbType="NVarChar(50)")]
		public string TenNS
		{
			get
			{
				return this._TenNS;
			}
			set
			{
				if ((this._TenNS != value))
				{
					this.OnTenNSChanging(value);
					this.SendPropertyChanging();
					this._TenNS = value;
					this.SendPropertyChanged("TenNS");
					this.OnTenNSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Anh
		{
			get
			{
				return this._Anh;
			}
			set
			{
				if ((this._Anh != value))
				{
					this.OnAnhChanging(value);
					this.SendPropertyChanging();
					this._Anh = value;
					this.SendPropertyChanged("Anh");
					this.OnAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(3)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiSinh", DbType="NVarChar(100)")]
		public string NoiSinh
		{
			get
			{
				return this._NoiSinh;
			}
			set
			{
				if ((this._NoiSinh != value))
				{
					this.OnNoiSinhChanging(value);
					this.SendPropertyChanging();
					this._NoiSinh = value;
					this.SendPropertyChanged("NoiSinh");
					this.OnNoiSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QueQuan", DbType="NVarChar(200)")]
		public string QueQuan
		{
			get
			{
				return this._QueQuan;
			}
			set
			{
				if ((this._QueQuan != value))
				{
					this.OnQueQuanChanging(value);
					this.SendPropertyChanging();
					this._QueQuan = value;
					this.SendPropertyChanged("QueQuan");
					this.OnQueQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoKhauThuongTru", DbType="NVarChar(200)")]
		public string HoKhauThuongTru
		{
			get
			{
				return this._HoKhauThuongTru;
			}
			set
			{
				if ((this._HoKhauThuongTru != value))
				{
					this.OnHoKhauThuongTruChanging(value);
					this.SendPropertyChanging();
					this._HoKhauThuongTru = value;
					this.SendPropertyChanged("HoKhauThuongTru");
					this.OnHoKhauThuongTruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="Int")]
		public System.Nullable<int> CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCap", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCap
		{
			get
			{
				return this._NgayCap;
			}
			set
			{
				if ((this._NgayCap != value))
				{
					this.OnNgayCapChanging(value);
					this.SendPropertyChanging();
					this._NgayCap = value;
					this.SendPropertyChanged("NgayCap");
					this.OnNgayCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiCap", DbType="NVarChar(50)")]
		public string NoiCap
		{
			get
			{
				return this._NoiCap;
			}
			set
			{
				if ((this._NoiCap != value))
				{
					this.OnNoiCapChanging(value);
					this.SendPropertyChanging();
					this._NoiCap = value;
					this.SendPropertyChanged("NoiCap");
					this.OnNoiCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuocTich", DbType="NVarChar(50)")]
		public string QuocTich
		{
			get
			{
				return this._QuocTich;
			}
			set
			{
				if ((this._QuocTich != value))
				{
					this.OnQuocTichChanging(value);
					this.SendPropertyChanging();
					this._QuocTich = value;
					this.SendPropertyChanged("QuocTich");
					this.OnQuocTichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TonGiao", DbType="NVarChar(50)")]
		public string TonGiao
		{
			get
			{
				return this._TonGiao;
			}
			set
			{
				if ((this._TonGiao != value))
				{
					this.OnTonGiaoChanging(value);
					this.SendPropertyChanging();
					this._TonGiao = value;
					this.SendPropertyChanged("TonGiao");
					this.OnTonGiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDanToc", DbType="VarChar(5)")]
		public string MaDanToc
		{
			get
			{
				return this._MaDanToc;
			}
			set
			{
				if ((this._MaDanToc != value))
				{
					if (this._DanToc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDanTocChanging(value);
					this.SendPropertyChanging();
					this._MaDanToc = value;
					this.SendPropertyChanged("MaDanToc");
					this.OnMaDanTocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCV", DbType="VarChar(5)")]
		public string MaCV
		{
			get
			{
				return this._MaCV;
			}
			set
			{
				if ((this._MaCV != value))
				{
					if (this._ChucVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCVChanging(value);
					this.SendPropertyChanging();
					this._MaCV = value;
					this.SendPropertyChanged("MaCV");
					this.OnMaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhongBan", DbType="VarChar(5)")]
		public string MaPhongBan
		{
			get
			{
				return this._MaPhongBan;
			}
			set
			{
				if ((this._MaPhongBan != value))
				{
					if (this._PhongBan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhongBanChanging(value);
					this.SendPropertyChanging();
					this._MaPhongBan = value;
					this.SendPropertyChanged("MaPhongBan");
					this.OnMaPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Int")]
		public System.Nullable<int> SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhomMau", DbType="VarChar(2)")]
		public string NhomMau
		{
			get
			{
				return this._NhomMau;
			}
			set
			{
				if ((this._NhomMau != value))
				{
					this.OnNhomMauChanging(value);
					this.SendPropertyChanging();
					this._NhomMau = value;
					this.SendPropertyChanged("NhomMau");
					this.OnNhomMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChieuCao", DbType="VarChar(10)")]
		public string ChieuCao
		{
			get
			{
				return this._ChieuCao;
			}
			set
			{
				if ((this._ChieuCao != value))
				{
					this.OnChieuCaoChanging(value);
					this.SendPropertyChanging();
					this._ChieuCao = value;
					this.SendPropertyChanged("ChieuCao");
					this.OnChieuCaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanNang", DbType="VarChar(10)")]
		public string CanNang
		{
			get
			{
				return this._CanNang;
			}
			set
			{
				if ((this._CanNang != value))
				{
					this.OnCanNangChanging(value);
					this.SendPropertyChanging();
					this._CanNang = value;
					this.SendPropertyChanged("CanNang");
					this.OnCanNangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SucKhoe", DbType="NVarChar(50)")]
		public string SucKhoe
		{
			get
			{
				return this._SucKhoe;
			}
			set
			{
				if ((this._SucKhoe != value))
				{
					this.OnSucKhoeChanging(value);
					this.SendPropertyChanging();
					this._SucKhoe = value;
					this.SendPropertyChanged("SucKhoe");
					this.OnSucKhoeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangHonNhan", DbType="NVarChar(50)")]
		public string TinhTrangHonNhan
		{
			get
			{
				return this._TinhTrangHonNhan;
			}
			set
			{
				if ((this._TinhTrangHonNhan != value))
				{
					this.OnTinhTrangHonNhanChanging(value);
					this.SendPropertyChanging();
					this._TinhTrangHonNhan = value;
					this.SendPropertyChanged("TinhTrangHonNhan");
					this.OnTinhTrangHonNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhPhanGiaDinh", DbType="NVarChar(500)")]
		public string ThanhPhanGiaDinh
		{
			get
			{
				return this._ThanhPhanGiaDinh;
			}
			set
			{
				if ((this._ThanhPhanGiaDinh != value))
				{
					this.OnThanhPhanGiaDinhChanging(value);
					this.SendPropertyChanging();
					this._ThanhPhanGiaDinh = value;
					this.SendPropertyChanged("ThanhPhanGiaDinh");
					this.OnThanhPhanGiaDinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DangVien", DbType="NVarChar(50)")]
		public string DangVien
		{
			get
			{
				return this._DangVien;
			}
			set
			{
				if ((this._DangVien != value))
				{
					this.OnDangVienChanging(value);
					this.SendPropertyChanging();
					this._DangVien = value;
					this.SendPropertyChanged("DangVien");
					this.OnDangVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayVaoDoan", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayVaoDoan
		{
			get
			{
				return this._NgayVaoDoan;
			}
			set
			{
				if ((this._NgayVaoDoan != value))
				{
					this.OnNgayVaoDoanChanging(value);
					this.SendPropertyChanging();
					this._NgayVaoDoan = value;
					this.SendPropertyChanged("NgayVaoDoan");
					this.OnNgayVaoDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayVaoDang", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayVaoDang
		{
			get
			{
				return this._NgayVaoDang;
			}
			set
			{
				if ((this._NgayVaoDang != value))
				{
					this.OnNgayVaoDangChanging(value);
					this.SendPropertyChanging();
					this._NgayVaoDang = value;
					this.SendPropertyChanged("NgayVaoDang");
					this.OnNgayVaoDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrinhDoVanHoa", DbType="NVarChar(50)")]
		public string TrinhDoVanHoa
		{
			get
			{
				return this._TrinhDoVanHoa;
			}
			set
			{
				if ((this._TrinhDoVanHoa != value))
				{
					this.OnTrinhDoVanHoaChanging(value);
					this.SendPropertyChanging();
					this._TrinhDoVanHoa = value;
					this.SendPropertyChanged("TrinhDoVanHoa");
					this.OnTrinhDoVanHoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotNghiep", DbType="NVarChar(50)")]
		public string TotNghiep
		{
			get
			{
				return this._TotNghiep;
			}
			set
			{
				if ((this._TotNghiep != value))
				{
					this.OnTotNghiepChanging(value);
					this.SendPropertyChanging();
					this._TotNghiep = value;
					this.SendPropertyChanged("TotNghiep");
					this.OnTotNghiepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NganhDaoTao", DbType="NVarChar(50)")]
		public string NganhDaoTao
		{
			get
			{
				return this._NganhDaoTao;
			}
			set
			{
				if ((this._NganhDaoTao != value))
				{
					this.OnNganhDaoTaoChanging(value);
					this.SendPropertyChanging();
					this._NganhDaoTao = value;
					this.SendPropertyChanged("NganhDaoTao");
					this.OnNganhDaoTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai", DbType="NVarChar(8)")]
		public string Loai
		{
			get
			{
				return this._Loai;
			}
			set
			{
				if ((this._Loai != value))
				{
					this.OnLoaiChanging(value);
					this.SendPropertyChanging();
					this._Loai = value;
					this.SendPropertyChanged("Loai");
					this.OnLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocVi", DbType="NVarChar(20)")]
		public string HocVi
		{
			get
			{
				return this._HocVi;
			}
			set
			{
				if ((this._HocVi != value))
				{
					this.OnHocViChanging(value);
					this.SendPropertyChanging();
					this._HocVi = value;
					this.SendPropertyChanged("HocVi");
					this.OnHocViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgoaiNgu", DbType="NVarChar(50)")]
		public string NgoaiNgu
		{
			get
			{
				return this._NgoaiNgu;
			}
			set
			{
				if ((this._NgoaiNgu != value))
				{
					this.OnNgoaiNguChanging(value);
					this.SendPropertyChanging();
					this._NgoaiNgu = value;
					this.SendPropertyChanged("NgoaiNgu");
					this.OnNgoaiNguChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoSoNhanSu_KyLuat", Storage="_KyLuats", ThisKey="MaNhanSu", OtherKey="MaNhanSu")]
		public EntitySet<KyLuat> KyLuats
		{
			get
			{
				return this._KyLuats;
			}
			set
			{
				this._KyLuats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoSoNhanSu_KhenThuong", Storage="_KhenThuongs", ThisKey="MaNhanSu", OtherKey="MaNhanSu")]
		public EntitySet<KhenThuong> KhenThuongs
		{
			get
			{
				return this._KhenThuongs;
			}
			set
			{
				this._KhenThuongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongBan_HoSoNhanSu", Storage="_PhongBan", ThisKey="MaPhongBan", OtherKey="MaPhongBan", IsForeignKey=true)]
		public PhongBan PhongBan
		{
			get
			{
				return this._PhongBan.Entity;
			}
			set
			{
				PhongBan previousValue = this._PhongBan.Entity;
				if (((previousValue != value) 
							|| (this._PhongBan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhongBan.Entity = null;
						previousValue.HoSoNhanSus.Remove(this);
					}
					this._PhongBan.Entity = value;
					if ((value != null))
					{
						value.HoSoNhanSus.Add(this);
						this._MaPhongBan = value.MaPhongBan;
					}
					else
					{
						this._MaPhongBan = default(string);
					}
					this.SendPropertyChanged("PhongBan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanToc_HoSoNhanSu", Storage="_DanToc", ThisKey="MaDanToc", OtherKey="MaDanToc", IsForeignKey=true)]
		public DanToc DanToc
		{
			get
			{
				return this._DanToc.Entity;
			}
			set
			{
				DanToc previousValue = this._DanToc.Entity;
				if (((previousValue != value) 
							|| (this._DanToc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DanToc.Entity = null;
						previousValue.HoSoNhanSus.Remove(this);
					}
					this._DanToc.Entity = value;
					if ((value != null))
					{
						value.HoSoNhanSus.Add(this);
						this._MaDanToc = value.MaDanToc;
					}
					else
					{
						this._MaDanToc = default(string);
					}
					this.SendPropertyChanged("DanToc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_HoSoNhanSu", Storage="_ChucVu", ThisKey="MaCV", OtherKey="MaCV", IsForeignKey=true)]
		public ChucVu ChucVu
		{
			get
			{
				return this._ChucVu.Entity;
			}
			set
			{
				ChucVu previousValue = this._ChucVu.Entity;
				if (((previousValue != value) 
							|| (this._ChucVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChucVu.Entity = null;
						previousValue.HoSoNhanSus.Remove(this);
					}
					this._ChucVu.Entity = value;
					if ((value != null))
					{
						value.HoSoNhanSus.Add(this);
						this._MaCV = value.MaCV;
					}
					else
					{
						this._MaCV = default(string);
					}
					this.SendPropertyChanged("ChucVu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KyLuats(KyLuat entity)
		{
			this.SendPropertyChanging();
			entity.HoSoNhanSu = this;
		}
		
		private void detach_KyLuats(KyLuat entity)
		{
			this.SendPropertyChanging();
			entity.HoSoNhanSu = null;
		}
		
		private void attach_KhenThuongs(KhenThuong entity)
		{
			this.SendPropertyChanging();
			entity.HoSoNhanSu = this;
		}
		
		private void detach_KhenThuongs(KhenThuong entity)
		{
			this.SendPropertyChanging();
			entity.HoSoNhanSu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanToc")]
	public partial class DanToc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDanToc;
		
		private string _TenDanToc;
		
		private EntitySet<HoSoNhanSu> _HoSoNhanSus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDanTocChanging(string value);
    partial void OnMaDanTocChanged();
    partial void OnTenDanTocChanging(string value);
    partial void OnTenDanTocChanged();
    #endregion
		
		public DanToc()
		{
			this._HoSoNhanSus = new EntitySet<HoSoNhanSu>(new Action<HoSoNhanSu>(this.attach_HoSoNhanSus), new Action<HoSoNhanSu>(this.detach_HoSoNhanSus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDanToc", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDanToc
		{
			get
			{
				return this._MaDanToc;
			}
			set
			{
				if ((this._MaDanToc != value))
				{
					this.OnMaDanTocChanging(value);
					this.SendPropertyChanging();
					this._MaDanToc = value;
					this.SendPropertyChanged("MaDanToc");
					this.OnMaDanTocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDanToc", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenDanToc
		{
			get
			{
				return this._TenDanToc;
			}
			set
			{
				if ((this._TenDanToc != value))
				{
					this.OnTenDanTocChanging(value);
					this.SendPropertyChanging();
					this._TenDanToc = value;
					this.SendPropertyChanged("TenDanToc");
					this.OnTenDanTocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanToc_HoSoNhanSu", Storage="_HoSoNhanSus", ThisKey="MaDanToc", OtherKey="MaDanToc")]
		public EntitySet<HoSoNhanSu> HoSoNhanSus
		{
			get
			{
				return this._HoSoNhanSus;
			}
			set
			{
				this._HoSoNhanSus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoSoNhanSus(HoSoNhanSu entity)
		{
			this.SendPropertyChanging();
			entity.DanToc = this;
		}
		
		private void detach_HoSoNhanSus(HoSoNhanSu entity)
		{
			this.SendPropertyChanging();
			entity.DanToc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChucVu")]
	public partial class ChucVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCV;
		
		private string _TenCV;
		
		private EntitySet<HoSoNhanSu> _HoSoNhanSus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCVChanging(string value);
    partial void OnMaCVChanged();
    partial void OnTenCVChanging(string value);
    partial void OnTenCVChanged();
    #endregion
		
		public ChucVu()
		{
			this._HoSoNhanSus = new EntitySet<HoSoNhanSu>(new Action<HoSoNhanSu>(this.attach_HoSoNhanSus), new Action<HoSoNhanSu>(this.detach_HoSoNhanSus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCV", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCV
		{
			get
			{
				return this._MaCV;
			}
			set
			{
				if ((this._MaCV != value))
				{
					this.OnMaCVChanging(value);
					this.SendPropertyChanging();
					this._MaCV = value;
					this.SendPropertyChanged("MaCV");
					this.OnMaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCV", DbType="NVarChar(100)")]
		public string TenCV
		{
			get
			{
				return this._TenCV;
			}
			set
			{
				if ((this._TenCV != value))
				{
					this.OnTenCVChanging(value);
					this.SendPropertyChanging();
					this._TenCV = value;
					this.SendPropertyChanged("TenCV");
					this.OnTenCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_HoSoNhanSu", Storage="_HoSoNhanSus", ThisKey="MaCV", OtherKey="MaCV")]
		public EntitySet<HoSoNhanSu> HoSoNhanSus
		{
			get
			{
				return this._HoSoNhanSus;
			}
			set
			{
				this._HoSoNhanSus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoSoNhanSus(HoSoNhanSu entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu = this;
		}
		
		private void detach_HoSoNhanSus(HoSoNhanSu entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu = null;
		}
	}
}
#pragma warning restore 1591
